image:
  file: .gitpod.dockerfile

# # List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# tasks:
#   - init: echo 'init script' # runs during prebuild
#     command: echo 'start script'

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
tasks:
  - name: bash history
    command: |
      sudo mkdir /workspace/.pers
      sudo touch /workspace/.pers/.bash_history
      sudo echo "HISTFILE = /workspace/.pers/.bash_history" >> /home/gitpod/.bash_profile
     
    